### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JuYeong0413** [CSID-DGU/2019-2-OSSP1-Haejwo-1#1]
- [x] Framework7 적용
- [x] Vuma 적용
- [ ] DB설계 - 진행중
- [ ] Admin 페이지
- [x] AWS 배포
- [ ] 안드로이드 앱 패키징

### 심부름(Event)
- [x] 목록(랜딩페이지)
- [ ] 생성(Create)
- [ ] 상세보기(Read)
- [ ] 수정(Update)
- [x] 삭제(Delete)
- [ ] 심부름 수락
- [ ] 상태관리
- [ ] Google Maps 표시
- [ ] 검색 및 필터

### 사용자(User)
- [ ] 회원가입
- [ ] 로그인
- [ ] 학생증 인증(사진)
- [ ] 이메일 인증(동국대학교 웹메일)
- [ ] 회원정보수정
- [ ] 회원탈퇴
- [ ] 사용자 신고

### 기타
- [ ] 푸시알림
- [ ] 채팅
- [ ] 소셜로그인
